### ISSUE TITLE
Code needs comments. Also code doesn't work for me.

### ISSUE THREAD

**Issue by rpbeltran** [lekro/Nong#3]
Also translations for foreign languages, and maybe morse code.

**Comment by rpbeltran** [comment]
That, and I can't get it to work, but that's no biggy.

**Comment by lekro** [comment]
Slowly working on the comments.

**Comment by rpbeltran** [comment]
Does it draw the paddles for you guys?

**Comment by lekro** [comment]
Yes, it does. But @legomaniack might not have committed that change.

**Comment by rpbeltran** [comment]
It doesn't for me, and I think it might be "n.drawScreen(); " from line 31 in ClientGameLoop.showUpdate() not doing anything

**Comment by rpbeltran** [comment]
Also, it freaks out when I press the down arrow.

**Comment by rpbeltran** [comment]
Anything I can help with? I need to make 4 pull requests, and I have.. zero done.

**Comment by lekro** [comment]
I just commented a lot of the code. 

It seemed to work last time, but some recent commit borked all the rendering. I'll try and fix.

**Comment by rpbeltran** [comment]
Just grabbed the updates. It's working for me now.
